### ISSUE TITLE
ToDo - Functions pt.2

### ISSUE THREAD

**Issue by HyperekDerg** [HyperekDerg/HiveHub#17]
- [x] Create new menu where user can select how to display users [By email - only one/ By ineterests - list everyone with this option and ask if you want to export list of this people/ Everyone and ask if you want to export list of this people]
- [x] Write all this functions
- [x] Test it when in database are 1,5,20 users. Use generator by chatGPT and copy records to database.txt
