### ISSUE TITLE
ToDo - Language Packs

### ISSUE THREAD

**Issue by HyperekDerg** [HyperekDerg/HiveHub#24]
- [ ] Create new files containing the language variables.
- [ ] Translate the messages accordingly.
- [ ] Implement in code.
