### ISSUE TITLE
ToDo - Database

### ISSUE THREAD

**Issue by HyperekDerg** [HyperekDerg/HiveHub#4]
- [x] Create files for database
- [x] Write a function for writing database records
- [x] Write a function for reading database records
- [x] Write a function to remove records from database

Focus on writing txt based database.
