### ISSUE TITLE
ToDo - Functions pt.1

### ISSUE THREAD

**Issue by HyperekDerg** [HyperekDerg/HiveHub#5]
- [x] Write function allowing adding new person - use database write function.
- [x] Write function allowing edit person interests
- [x] Write function allowing removing people from the database
