### ISSUE TITLE
ToDo - Documentation and final code review 

### ISSUE THREAD

**Issue by HyperekDerg** [HyperekDerg/HiveHub#6]
- [x] Create block schemes for this project 
- [x] Write a txt file about this project. Make sure to check if everything is correctly written.
- [x] Review again code. Remove unnecessary spaces, comments, lines.
